"""baseline

Revision ID: 71405c3773d1
Revises: Create Date: 2021-06-04 21:21:20.133254
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '71405c3773d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeworks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('deadline', sa.DateTime(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Result',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('homework_id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.Column('solve', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['homework_id'],
                                            ['homeworks.id'], ),
                    sa.ForeignKeyConstraint(['student_id'],
                                            ['students.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'],
                                            ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Result')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('homeworks')
    # ### end Alembic commands ###
